-- Flavor taxonomy seed. Source of truth mirrored in flavor-taxonomy.js.
INSERT INTO flavor_tags (name, category) VALUES
('caramel', 'sweet'), ('vanilla', 'sweet'), ('brown_sugar', 'sweet'), ('maple', 'sweet'),
('honey', 'sweet'), ('molasses', 'sweet'), ('butterscotch', 'sweet'), ('brueleed_sugar', 'sweet'),
('marshmallow', 'sweet'),
('toasted_oak', 'oak'), ('fresh_oak', 'oak'), ('charred_oak', 'oak'), ('mature_oak', 'oak'),
('dry_oak', 'oak'), ('tannic_oak', 'oak'),
('cherry', 'fruit'), ('dark_cherry', 'fruit'), ('medicinal_cherry', 'fruit'), ('apple', 'fruit'),
('pear', 'fruit'), ('orange', 'fruit'), ('raisin', 'fruit'), ('fig', 'fruit'), ('berry', 'fruit'),
('stone_fruit', 'fruit'), ('tropical_fruit', 'fruit'),
('cinnamon', 'spice'), ('clove', 'spice'), ('pepper', 'spice'), ('rye_spice', 'spice'),
('baking_spice', 'spice'), ('chili', 'spice'),
('chocolate', 'rich_dessert'), ('cocoa', 'rich_dessert'), ('coffee', 'rich_dessert'),
('mocha', 'rich_dessert'), ('vanilla_cream', 'rich_dessert'), ('toffee', 'rich_dessert'),
('praline', 'rich_dessert'), ('nutty', 'rich_dessert'), ('sweet_tobacco', 'rich_dessert'),
('toasted_marshmallow', 'rich_dessert'),
('mint', 'herbal'), ('eucalyptus', 'herbal'), ('anise', 'herbal'), ('herbal', 'herbal'),
('medicinal', 'herbal'), ('floral', 'herbal'),
('corn', 'grain'), ('wheat', 'grain'), ('rye_grain', 'grain'), ('malt', 'grain'),
('cereal', 'grain'), ('bread', 'grain'),
('smoke', 'smoke_earth'), ('peat', 'smoke_earth'), ('tobacco', 'smoke_earth'),
('leather', 'smoke_earth'), ('earth', 'smoke_earth'),
('rich_mouthfeel', 'texture'), ('thin_mouthfeel', 'texture'), ('rounded_finish', 'texture'),
('dessert_like_finish', 'texture'), ('excessive_dryness', 'texture'), ('hot_ethanol', 'texture'),
('bitter_oak', 'texture'), ('double_oaked', 'texture');
